@baseUrl = http://localhost:8080
@super_admin_email = admin@camera-rental.test
@admin_email = rental@camera-rental.test
@password = admin123

### Login super admin
# @name login_super_admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{super_admin_email}}",
  "password": "{{password}}"
}

### Login admin biasa
# @name login_admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "{{admin_email}}",
  "password": "{{password}}"
}

### App info
GET {{baseUrl}}/api
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Logout super admin
DELETE {{baseUrl}}/api/auth/logout
Authorization: Bearer {{login_super_admin.response.body.data.token}}

