@baseUrl = http://localhost:8080

### Login super admin
# @name login_super_admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@camera-rental.test",
  "password": "admin123"
}

### Get admins with pagination
GET {{baseUrl}}/api/admins?page=0&size=10
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Search admins
GET {{baseUrl}}/api/admins?page=0&size=10&search=rental
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Filter admins
GET {{baseUrl}}/api/admins?page=0&size=10&role=admin&sort=name&direction=asc
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Date filter admins
GET {{baseUrl}}/api/admins?page=0&size=10&start_date=2026-01-01&end_date=2026-12-31
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Get admin by id
GET {{baseUrl}}/api/admins/1
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Create admin
POST {{baseUrl}}/api/admins
Authorization: Bearer {{login_super_admin.response.body.data.token}}
Content-Type: application/json

{
  "name": "Admin Demo Baru",
  "email": "admin.demo@camera-rental.test",
  "password": "admin123",
  "role": "admin"
}

### Update admin
PUT {{baseUrl}}/api/admins/2
Authorization: Bearer {{login_super_admin.response.body.data.token}}
Content-Type: application/json

{
  "name": "Admin Rental Updated",
  "email": "rental@camera-rental.test",
  "password": "",
  "role": "admin"
}

### Delete admin
DELETE {{baseUrl}}/api/admins/3
Authorization: Bearer {{login_super_admin.response.body.data.token}}

