@baseUrl = http://localhost:8080

### Login super admin
# @name login_super_admin
POST {{baseUrl}}/api/auth/login
Content-Type: application/json

{
  "email": "admin@camera-rental.test",
  "password": "admin123"
}

### List category details by category
GET {{baseUrl}}/api/categories-detail/get/1
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Detail category detail
GET {{baseUrl}}/api/category-details/1
Authorization: Bearer {{login_super_admin.response.body.data.token}}

### Create category detail by category
POST {{baseUrl}}/api/categories-detail/create/3
Authorization: Bearer {{login_super_admin.response.body.data.token}}
Content-Type: application/json

{
  "name": "Memory Card",
  "description": "Kartu memori dan storage"
}

### Update category detail by category
PUT {{baseUrl}}/api/categories-detail/update/1/1
Authorization: Bearer {{login_super_admin.response.body.data.token}}
Content-Type: application/json

{
  "name": "Mirrorless",
  "description": "Kamera mirrorless untuk foto dan video profesional"
}

### Delete category detail by category
DELETE {{baseUrl}}/api/categories-detail/delete/3/7
Authorization: Bearer {{login_super_admin.response.body.data.token}}
